receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  resource:
    attributes:
      - key: deployment.environment
        value: ${ENVIRONMENT}
        action: upsert
      - key: service.namespace
        value: mlops_assessment
        action: upsert

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: mlops_assessment
    
  debug:
    verbosity: detailed
    
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [debug, otlp/jaeger]
      
    metrics:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [debug, prometheus]
